{% set name = "pygments.rb" %}
{% set version = "3.0.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 41729ecc69624bd3fc6bcc13d6ccb6ff0263334c42f66bfcf517a120addbb093

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r pygments.rb -e 'exit 0'

about:
  home: https://rubygems.org/gems/pygments.rb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pygments.rb is a Ruby wrapper for Pygments syntax highlighter

  doc_url: https://www.rubydoc.info/gems/pygments.rb
  dev_url: https://github.com/pygments/pygments.rb

extra:
  recipe-maintainers:
    - ajaypnair09
